/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SmartWardrobe;

import SmartWardrobe.*;
import java.awt.Color;
import java.awt.*;
import javax.swing.*;
import SmartWardrobe.WardrobeClient;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;




/**
 *
 * @author Paul
 */
public class WardrobeGUI extends javax.swing.JFrame {
    
    public WardrobeClient client;
    
    
    
    /**
     * Creates new form MirrorGUI
     */
    public WardrobeGUI() {
        initComponents();
        
    }
    
    public WardrobeGUI(WardrobeClient client) {
        this();
        this.client = client;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        robotArm = new javax.swing.JLabel();
        powerLight = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        powerBtn = new javax.swing.JButton();
        robotStatusMsg = new javax.swing.JLabel();
        xTF = new javax.swing.JTextField();
        yTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("H6");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel2.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 90, 140));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("H1");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel3.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 140));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("H5");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel4.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 80, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("H4");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel5.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 80, 140));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("H3");
        jLabel6.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel6.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 90, 140));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("H2");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel7.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 140));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("H8");
        jLabel8.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel8.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 80, 140));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("H7");
        jLabel9.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel9.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 80, 140));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel10.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 140));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel11.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 140));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel12.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 90, 140));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 0));
        jLabel13.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel13.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 80, 140));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 0));
        jLabel14.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel14.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 80, 140));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel15.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 90, 140));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 204, 0));
        jLabel16.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel16.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 80, 140));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 204, 0));
        jLabel17.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel17.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 80, 140));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 204, 0));
        jLabel18.setText("H14");
        jLabel18.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel18.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, 140));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setText("H9");
        jLabel19.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel19.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 90, 140));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 204, 0));
        jLabel20.setText("H13");
        jLabel20.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel20.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 80, 140));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 204, 0));
        jLabel21.setText("H12");
        jLabel21.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel21.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 80, 140));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 204, 0));
        jLabel22.setText("H11");
        jLabel22.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel22.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 90, 140));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 204, 0));
        jLabel23.setText("H10");
        jLabel23.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel23.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, 140));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 204, 0));
        jLabel24.setText("H16");
        jLabel24.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel24.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 80, 140));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 204, 0));
        jLabel25.setText("H15");
        jLabel25.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel25.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 80, 140));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 204, 0));
        jLabel26.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel26.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 90, 140));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 204, 0));
        jLabel27.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel27.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 80, 140));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 204, 0));
        jLabel28.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel28.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 90, 140));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 204, 0));
        jLabel29.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel29.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 80, 140));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 204, 0));
        jLabel30.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel30.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 80, 140));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 204, 0));
        jLabel31.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel31.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 90, 140));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 204, 0));
        jLabel32.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel32.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 80, 140));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 204, 0));
        jLabel33.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel33.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 80, 140));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 204, 0));
        jLabel34.setText("H20");
        jLabel34.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel34.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 140));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 204, 0));
        jLabel35.setText("H17");
        jLabel35.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel35.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 90, 140));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 204, 0));
        jLabel36.setText("H21");
        jLabel36.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel36.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 80, 140));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 204, 0));
        jLabel37.setText("H19");
        jLabel37.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel37.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 90, 140));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 204, 0));
        jLabel38.setText("H24");
        jLabel38.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel38.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 80, 140));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 204, 0));
        jLabel39.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel39.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 80, 140));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 204, 0));
        jLabel40.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel40.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 90, 140));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 204, 0));
        jLabel41.setText("H18");
        jLabel41.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel41.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 80, 140));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 204, 0));
        jLabel42.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel42.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 80, 140));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 204, 0));
        jLabel43.setText("H23");
        jLabel43.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel43.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 80, 140));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 204, 0));
        jLabel44.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel44.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 80, 140));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 204, 0));
        jLabel45.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel45.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 140));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 204, 0));
        jLabel46.setText("H22");
        jLabel46.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel46.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 90, 140));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(51, 204, 0));
        jLabel47.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel47.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 80, 140));

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(51, 204, 0));
        jLabel48.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel48.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 90, 140));

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(51, 204, 0));
        jLabel49.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel49.setMaximumSize(new java.awt.Dimension(82, 35));
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 90, 140));

        robotArm.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        robotArm.setForeground(new java.awt.Color(255, 0, 0));
        robotArm.setText("+");
        jPanel1.add(robotArm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        powerLight.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        powerLight.setForeground(new java.awt.Color(255, 0, 0));
        powerLight.setText("*");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Smart Wardrobe");

        powerBtn.setText("Power");
        powerBtn.setActionCommand("powerBtn");
        powerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                powerBtnMouseClicked(evt);
            }
        });

        robotStatusMsg.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        robotStatusMsg.setText("Status :");

        jButton1.setText("GET ITEM");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(robotStatusMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(powerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(powerLight))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(xTF, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(yTF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(robotStatusMsg)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(powerLight)
                            .addComponent(powerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void powerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powerBtnMouseClicked
//        try {
            // TODO add your handling code here:
        client.powerOnOff();
//moveArm(500,100);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(WardrobeGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
//      
    }//GEN-LAST:event_powerBtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int x = Integer.parseInt(xTF.getText());	
        int y = Integer.parseInt(yTF.getText());	
        
        client.getItem(x, y);
    }//GEN-LAST:event_jButton1MouseClicked

    public void changePwrColor (Boolean status) {
        

        if(!status.equals(true)){
            powerLight.setForeground(Color.red);
            powerLight.setAlignmentX(10);
          
        }
        else {
        powerLight.setForeground(Color.GREEN);
         
        }
    }
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WardrobeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WardrobeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WardrobeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WardrobeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WardrobeGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton powerBtn;
    private javax.swing.JLabel powerLight;
    private javax.swing.JLabel robotArm;
    private javax.swing.JLabel robotStatusMsg;
    private javax.swing.JTextField xTF;
    private javax.swing.JTextField yTF;
    // End of variables declaration//GEN-END:variables
    
    
    public void moveArmX (int newXCoor ){
        Point pt = robotArm.getLocation();
        
        int xNewPos = pt.x;
        if (newXCoor == 0) {
            xNewPos = 0;
        }
        else {
            xNewPos = (newXCoor * 90);
        }
        System.out.println(xNewPos);
        
        
        robotArm.setLocation(xNewPos, pt.y); 
    }
    
public void moveArmY (int newYCoor ){
        Point pt = robotArm.getLocation();
        
        int yNewPos = pt.y;
        if (newYCoor == 0) {
            yNewPos = 0;
        }
        else {
            yNewPos = (newYCoor * 142);
        }
        System.out.println(yNewPos);
        robotArm.setLocation(pt.x, yNewPos);         
    }
    
    public void grabItem (){
        robotArm.setForeground(Color.GREEN);    
    }
    
    
    public void changeStatusMsg(String string) {
        robotStatusMsg.setText("Status : " + string);
    }
//
//    public void append(String string) {
//        infoArea.append(string +"\n\n");
//    }

//    public void clear() {
//        infoArea.setText("");
//    }
}
